fireworks:
  max-explosions: 25
signs:
  max-characters-per-line: 16
books:
  max-book-page-size: 2560
  max-book-total-size-multiplier: 0.98

  ## Enable this if you don't need any book functionality on your server.
  no-books: false
limits:
  ## There is no perfect value for this.
  ## In order to prevent people getting kicked for lag, the max PPS is higher than shown below.
  ## Every server is different, you'll have to find a good value yourself.
  ## I got this value by assuming a player is clicking 20 CPS, moving, and receiving 2 transactions a tick.
  ## I am also assuming a player could possibly lagspike for 15 seconds, allowing them to send 1200 packets in one second.
  max-packets-per-second: 500

  ## This is the maximum readable bytes a ByteBuf is allowed to contain.
  ## You might want this lower or higher depending on your server and server version.
  ## Every server is different, you'll have to find a good value yourself.
  ## Set to -1 to disable
  max-bytes: 64000
spam:
  ## Packet names can be found @ https://wiki.vg/Protocol in the Serverbound section.
  ## Valid format: HELD_ITEM_CHANGE or HELD ITEM CHANGE (Capitalization does not matter.)
  multipliers:
    HELD_ITEM_CHANGE: 1.0
    ANIMATION: 1.0
